name: example
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0
dev_dependencies:
  lint: ^1.3.1
  test: ^1.14.4

dependencies:
  http: ^0.12.2
  cache:
    path: ../../cache
