name: example
description: A sample command-line application.

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  lint: ^1.3.1
  test: ^1.14.4

dependencies:
  cache_it:
    path: ../
  http: ^0.12.2
