name: example
description: A sample command-line application.

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  lint: ^1.5.1
  test: ^1.14.4

dependencies:
  cache_it:
    path: ../
  http: ^0.13.0-nullsafety.0
