name: example
description: A sample command-line application.

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lint: ^1.7.2
  test: ^1.19.1

dependencies:
  cache_it:
    path: ../
  equatable: ^2.0.3
  http: ^0.13.4
