name: cache_it
description: A simple object cache implementation
version: 0.1.0-nullsafety.0
homepage: https://github.com/berbsd/flutter-cache
repository: https://github.com/berbsd/flutter-cache.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:

  
dev_dependencies:
  lint: ^1.5.1
  test: ^1.16.0-nullsafety.13

